// Languages
export const Languages = [
	{ key: 2, label: 'English', code: 'en', isRTL: false, isDefault: true },
	{ key: 1, label: 'العربية', code: 'ar', isRTL: true, isDefault: false },
	{ key: 3, label: 'Turkish', code: 'tr', isRTL: false, isDefault: false },
	{ key: 4, label: 'Deutsche', code: 'de', isRTL: false, isDefault: false },
	{ key: 5, label: 'French', code: 'fr', isRTL: false, isDefault: false },
];

//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const en = {
	Login: 'Login',
	CantHaveEmptyInputs: 'Please fill in all inputs',
	InvalidEmail: 'Invalid email',
	InvalidPhone: 'Invalid phone number',
	TooShortPassword: 'Too short password',
	Signup: 'Sign up',
	Logout: 'Logout',
	Email: 'Email',
	Phone: 'Phone',
	Password: 'Password',
	ChangePassword: 'Change Password',
	English: 'English',
	Arabic: 'Arabic',
	noInternet: "No internet",
	connectionAvailable: "connection available",
	offlineNotice: "Your device is not connected to the internet, please make sure your connection is working.",
	tryAgain: "try again...",
	skip: "Skip",
	Orders: "Orders",
	Order: "Order",
	Products: "Products",
	Inbox: "Inbox",
	Analytics: "Analytics",
	More: "More",
	Home: "Home",
	Back: "Back",
	Files: 'Files',
	InternalServerErrorTitle: "Server problems",
	InternalServerErrorBody: "Server problems. Please try again later.",
	NotFoundServerErrorTitle: "Not found",
	NotFoundServerErrorBody: "Data not found. Please try something else.",
	FloodServerErrorTitle: "Temporarily blocked",
	FloodServerErrorBody: "Don't spam.",
	ValidationServerErrorTitle: "Incorrect data",
	ValidationServerErrorBody: "Incorrect data. Please check and try again.",
	LogicalServerErrorTitle: "Can't do that",
	Notifications: "Notifications",

	WalkthroughBodyContent1: "Your Store at Your Fingertips",
	WalkthroughBodyContent2: "Enjoy Watching Your Store Growing",
	WalkthroughBodyContent3: "Simple, Effective, Powerful Orders Management",
	WalkthroughBodyContent4: "Need More? We Cover You",
	WalkthroughBodyContent5: "Unlimited Categories, Products, Options and Brands",
	WalkthroughBodyContent6: "Control Everything, Anything at Anytime",
	WalkthroughBodyContent7: "Dream, Plan,  Make it Real",
	WalkthroughBodyContent8: "Manage Roles and Permissions as you wish",

	FailedLogin: "User not found or wrong password",
	Sessions: "Sessions",
	Brands: "Brands",
	Brand: "Brand",
	PleaseWait: "Please wait",
	Categories: "Categories",
	Name: "Name",
	FirstName: "First Name",
	LastName: "Last Name",
	ShortDescription: "Short Description",
	Description: "Description",
	Website: "Website",
	Editor: "Editor",
	EditDescInEditor: "Edit Long Description in editor",
	RichTextEditor: "Rich text editor",
	EditContentInEditor: "Edit content in editor",
	InvalidURL: "Invalid URL",
	ImageRequired: "Image is missing",
	Translation: "Translation",
	dataSaved: "Data saved successfully!",
	dataDeleted: 'Data Deleted successfully!',
	Cancel: "Cancel",
	Confirm: "Confirm",
	Search: "Search",
	TranslationKey: "Key",
	SourceText: "Source text",
	TargetText: "Target text",
	ProductOptions: "Product Options",
	ProductOptionsMembers: "Product Option Members",
	ProductOptionGroups: "Product options groups",
	AreYouSure: "Are you sure you want to perform this action?",
	Users: "Users",
	User: "User",
	IconSelector: 'Icon Selector',
	MobileIcon: "Mobile Icon",
	Members: "Members",
	iconColor: "icon / color",
	color: "color",
	shortCode: "short Code",
	Language: "Language",
	Info: "Info",
	Security: "Security",
	PersonalInfo: "Personal Info",
	Permissions: "Permissions",
	Permission: "Permission",
	LoginHistory: "Login History",
	LoginAccount: "Login Account",
	Address1: "Address 1",
	Address2: "Address 2",
	CurrencyList: "Currency List",
	SelectPlace: "Select Place",
	Country: "Country",
	Countries: "Countries",
	City: "City",
	Area: "Area",
	PassDontMatch: 'Passwords do not match',
	ConfirmPassword: "Confirm Password",
	InvalidPasswordFormat: "Password must contain at least one uppercase letter, lowercase letter, special character and number",
	ETags: 'eTags',
	ETag: 'eTag',
	createNewetag: "create a new eTag",
	NS_NewOrder: 'New Order',
	NS_NewMessage: 'New Message',
	NS_SecurityActions: 'Security Actions',
	NS_Reviews: 'Reviews',
	NS_Questions: 'Questions',
	NS_AskForPrice: 'Ask for Price',
	NS_AutoDiscount: 'Auto Discount',
	NS_StatisticsAlert: 'Statistics Alert',
	Role: 'Role',
	Warehouses: 'Warehouses',
	AddUser: 'Add User',
	Products: 'Products',
	UserAlreadyExists: 'User already exists',
	Customers: 'Customers',
	NoneSelected: 'None',
	Clear: 'Clear',
	Type: 'Type',
	Status: 'Status',
	Address: 'Address',
	Store: 'Store',
	Stores: 'Stores',
	Statistics: 'Statistics',
	VirtualMoney: 'Virtual Money',
	Spent: 'Spent',
	Gender: 'Gender',
	Facebook: 'Facebook',
	Twitter: 'Twitter',
	Birthday: 'Birthday',
	EnterConfirmCode: "Please enter the confirmation you've just received",
	IncorrectInput: 'Incorrect Input',
	Roles: 'Roles',
	MustHaveOneRole: 'Must have at least one role remaining',
	CanRead: 'Read',
	CanCreate: 'Create',
	CanEdit: 'Edit',
	CanDelete: 'Delete',
	Delete: 'Delete',
	CanExport: 'Export',
	Discounts: 'Discounts',
	Filters: 'Filters',
	Active: 'Active',
	Inactive: 'Inactive',
	Both: 'Both',
	Customer: "Customer",
	Courier: "Courier",
	Discount: "Discount",
	Select: "Select",
	ApplyFor: "Apply For",
	Restriction: "Restriction",
	CouponCode: "Code",
	RequiresCouponCode: "Requires Code",
	DiscountType: "Discount Type",
	DiscountLimitation: "Discount Limitation",
	LimitationTimes: "Limitation Times",
	DiscountPercentage: "Discount Percentage",
	DiscountAmount: "Discount Amount",
	MaximumDiscountAmount: "Max Discount Amount",
	ShowInWebsite: "Show on Application",
	StartDate: "Start Date",
	EndDate: "End Date",
	IsCumulative: "Cumulative",
	ApplyForChildCategory: "Include sub-categories",
	SpentAmountRestriction: "Spent amount",
	Shipping: "Shipping",
	CouponCodeDuplicated: "Coupon Code Duplicated",
	Articles: "Articles",
	Article: "Article",
	ParentArticle: "Parent Article",
	Icon: "Icon",
	Stories: "Stories",
	Story: "Story",
	Hours: "Hours",
	Days: "Days",
	Weeks: "Weeks",
	Length: "Length",
	Likes: "Likes",
	Views: "Views",
	TextColor: "Text Color",
	BackgroundColor: "Background Color",
	Summary: "Summary",
	Items: "Items",
	Item: "Item",
	TrackingHistory: "Tracking History",
	Chat: "Chat",
	SubTotal: "Sub-total",
	Tax: "Tax",
	Total: "Total",
	Details: "Details",
	CreatedDate: "Created Date",
	DeliveredDate: "Delivered Date",
	OrderCode: "Order Code",
	Save: 'Save',
	Advance_Settings: "Advance Settings",
	Courier_Config: 'Courier Configuration',
	Courier: 'Courier',
	AdvanceSettings: "Advance Settings",
	Price: "Price",
	RealPrice: "RealPrice",
	SalePrice: "SalePrice",
	SaleExpirationDate: "Sale expiration date",
	MaxPurchaseCount: "Max Purchase Count",
	Currency: "Currency",
	priceSteps: "price steps",
	PricingHistory: "Pricing history",
	Pricing: 'Pricing',
	Tags: 'Tags',
	TypeNewTagHere: 'Type a new tag here',
	LowStep: "Low step",
	HighStep: "High step",
	Add: "Add",
	UpdateCost: "Update cost",
	Where_Houses: 'WareHouses',
	Shoping_Speed: 'Shopping Speed',
	Quantity: "Quantity",
	Change: "Change",
	FixedPrice: "Fixed Price",
	KgPrice: "Kg Price",
	Key1: "Key 1",
	Key2: "Key 2",
	Key3: "Key 3",
	Key4: "Key 4",
	SecurityKey: "Security Key",
	HavePutOneKey: 'Enter At Least One Key',
	PleaceSelectCites: ' Select Cites',
	PleaceEnterKgPrice: ' Enter Kg Price',
	ToCity: 'To Cities',
	ToArea: 'To Areas',
	FromCity: 'From Cities',
	ToCountry: 'To Countries',
	FromCountry: 'From Countries',
	PleaceEnterFixedPrice: 'Enter Fixed Price',
	PleaceSelectWherehouse: 'Select warehouse',
	PleaceSelectShoppingspeed: 'Select Shopping speed',
	ExtraDetails: "Extra Details",
	DoneSuccessfully: "Done Successfully",
	Soon: "Soon",
	SeeMore: "See More",
	SeeLess: "See Less",
	CustomerType: 'Customer Type',
	ResetPassword: 'Reset Password',
	SelectLanguage: 'Select Language',
	overwrite: 'Overwrite',
	Done: 'Done',
	Images: 'Images',
	isreplaceableimage: 'is replaceable image',
	AdminTranslation: "Admin Translation",
	AppTranslation: "App Translation",
	SendAnswers: 'Send',
	Answer: 'Write Answer',
	AnswerSended: 'Your Answer has been sent',
	Answers: 'Answers',
	Approved: 'Approved',
	NotApproved: 'Not Approved',
	Replied: 'Replied',
	NotReplied: 'Not Replied',
	NoFilter: 'No Filter',
	ReviewDate: 'Review Date',
	ApproveDate: 'Approve Date',
	OrderReview: 'Order Review',
	OrderId: 'Order Id',
	Reply: 'Reply',
	ReplyText: 'Reply Text',
	DiscountPercentageValue: 'Discount Percentage must be Less Than or Equal 100 %',
	NegativeValidation: 'You Can\'t use negative number',
	DateValidation: 'End Date Can\'t be Smaller Than Start Date',
	Location: "Location",
	Rating: "Rating",
	SKU: 'SKU Is Required',
	ParentCategory: 'Parent Category',
	selected: 'Selected',
	Physical: 'Physical',
	Settings: 'Settings',
	Media: 'Media',
	Options: 'Options',
	Numberofdownloadsperday: 'Number of downloads per day',
	Numberofdaysdownloadavailable: 'Number of days download available',
	Purchasefile: 'Purchase file',
	Number: 'Number',
	filetypenotsupported: 'file type not supported',
	exceededfilesizelimit: 'exceeded file size limit',
	nooptionsfound: 'no options found',
	Height: 'Height',
	Weight: 'Weight',
	LocalLocation: 'Local Location',
	ManufacturerPartNumber: 'Manufacturer Part Number',
	pleaseenteraprice: 'please enter a price',
	pleaseenterarealprice: 'please enter a real price',
	Lowstepvaluecantbeempty: 'Low step value can\'t be empty',
	Highstepvaluecantbeempty: 'High step value can\'t be empty',
	Steppricevalue: 'Step price value can\'t be empty',
	LowstepcantbelowerthanTwo: 'Low step can\'t be lower than Two',
	Highstepmustbehigherthanlowstep: 'High step must be higher than low step',
	Enablereviews: 'Enable reviews',
	Enablequestions: 'Enable questions',
	Category: 'Category',
	Etag: 'Etag',
	PriceRange: 'Price range',
	RATINGRANAGE: 'Rating range',
	SelectProductType: 'Select Product Type',
	SelectProductVisibility: 'Select Product Visibility',
	SelectCategory: 'Select Category',
	DataNotSaved: 'Data Not Saved',
	Product: 'Product',
	Howmany: 'How many',
	in1usd: 'in 1 usd?',
	Text: 'Text',
	Questions: 'Questions',
	Reviews: 'Reviews',
	QuestionText: 'Question Text',
	Question: 'Question',
	Demofile: 'Demo file',
	Visibility: 'Visibility',
	cantdownload: 'can\'t download',
	Width: 'Width',
	StoreProfile: 'Store Profile',
	StoreName: 'Store Name',
	Profile: 'Profile',
	Languages: 'Languages',
	StoreListing: 'Store Listing',
	NOTIFICATIONS: 'NOTIFICATIONS',
	label: 'label',
	StoreList: 'Store List',
	NameOnStoreCantbeleththan3charchter: 'Store Name Can\'t be less than 3 characters',
	LongDescriptionCantbeleththan3charchter: 'Long Description Can\'t be less than 30 characters',
	ShortDescriptionCantbeleththan3charchter: 'Short Description Can\'t be less than 30 characters',
	LabelNameCantbeleththan3charchter: 'Label Name Can\'t be less than 3 characters',
	LongDescription: 'Long Description',
	Theme: 'Theme',
	StoreStyle: 'Store Style',
	FontSizeValidation: 'Font Size Must Less Than 30 and More Than 10',
	MainColor: 'Main Color',
	SecondColor: 'Second Color',
	ThirdColor: 'Third Color',
	Fonts: 'Fonts',
	Color: 'Color',
	FontSize: 'FontSize',
	FontType: 'FontType',
	AuthThemeType: 'Auth Theme Type',
	StoreThemeType: 'Store Theme Type',
	UserThemeType: 'User Theme Type',
	Sizes: 'Sizes',
	BorderRadius: 'Border Radius',
	Padding1: 'Padding1',
	Padding2: 'Padding2',
	Padding3: 'Padding3',
	Margin1: 'Margin1',
	Margin2: 'Margin2',
	Margin3: 'Margin3',
	Adress: 'Address',
	Default: 'Default',
	DefaultLanguage: 'Default Language',
	SecondName: 'Second Name',
	Email1: 'Email1',
	Email2: 'Email2',
	Address1: 'Address1',
	Address2: 'Address2',
	PostCode: 'Post Code',
	IsCompany: 'Is Company',
	CompanyName: 'Company Name',
	SetDefault: 'Set As Default',
	ShareAdress: 'Share Address',
	AddressHasBeenSet: 'Address has been set',
	EnterCompanyName: 'Enter company name',
	Open: 'Open',
	Close: 'Close',
	WorkingHours: 'Working Hours',
	From: 'From',
	To: 'To',
	IsOpen: 'Is Open?',
	BasicInfo: 'Basic Info',
	GpsCheckin: 'GPS Check-in',
	Warehouse: 'Warehouse',
	ShippingTypes: 'Shipping Types',
	AddWarehouse: 'Add Warehouse',
	Gps: 'Make Sure You Have Connection and GPS Is Opened',
	FullName: 'Full Name',
	Pages: 'Pages',
	MoreThanOne: 'Must More Than One',
	dataReset: 'Data Reset',
	Defaultfont: 'Default Font',
	SubStore: 'Sub Store',
	Payment: 'Payment',
	Payment_Config: 'Payment Config',
	FeesPercentage: 'Fees Percentage',
	FeesFixed: 'Fees Fixed',
	ProviderKey1: 'ProviderKey1',
	ProviderKey2: 'ProviderKey2',
	ProviderKey3: 'ProviderKey3',
	ProviderKey4: 'ProviderKey4',
	GetPricing: 'Get Pricing',
	NewOrder: 'New Order',
	Qty: 'Quantity',
	AddProduct: 'Add Product',
	Title: 'Title',
	AddIcon: 'Add Icon',
	Driver: 'Driver',
	IsRequired: 'Is Required',
	PleaseWait: 'Please Wait...',
	ProductOption: 'Product Option',
	Member: 'Member',
	Group: 'Group',
	notselected: 'not selected',
	Pricechange: 'Price change',
	AnswerNow: 'Answer',
	Porvider: 'Provider',
	Saving: 'Saving',
	Comission: 'Commission',
	IsDriver: 'Is Driver',
	Intro: 'Please Enter some data, that required to publish your app To App Store',
	GoLive: 'Go Live:',
	GoLiveTitle: 'Go Live',
	Info2: 'Your app will be available on App Stores after 2 Weeks of entering the data we asked you about in this page',
	Completed: 'Completed',
	Brofite: 'profit',
	Store_Name: 'Store Name',
	Store_Style: 'Store Style',
	Store_Listing: 'Store Listing',
	Shipping_Method: 'Shipping Method',
	Payment_Method: 'Payment Method',
	Logo: 'Logo',
	Config_Page: 'Config Page',
	TenProducts: '10 Products',
	TenCategory: '10 Category',
	AddNewForCustomer: '+ Add New',
	assignTODriver: 'Assign to Driver',
	Notes: 'Notes',
	Send: 'Send',
	Color4: 'Color4',
	Color5: 'Color5',
	Color6: 'Color6',
	Color7: 'Color7',
	Color8: 'Color8',
	Color9: 'Color9',
	Color10: 'Color10',
	TodayViews: 'Today Views',
	YesterdayViews: 'Yesterday Views',
	ThisWeekViews: 'This Week Views',
	ThisMonthViews: 'This Month Views',
	Days30BeforeViews: 'Days 30 Before Views',
	Days7BeforeViews: 'Days 7 Before Views',
	Analystic: 'Analystics',
	WeDontHaveTheLatitudeAndLongtude: 'We Don\'t Have The Latitude And Longitude',
	DeliverMap: 'Deliver Map',
	Accept: 'Accept',
	Decline: 'Decline',
	AcceptOrDeclineOrderNow: 'Accept or Decline Order Now',
	LessThanZero: ' Value Can\'t be Less Than Zero',
	ProductQtyStep: 'Quantity Step',
	ProductMinQty: 'Min Quantity',
	ProductMaxQty: 'Max Quantity',
	bgColor1: 'background Color 1',
	bgColor2: 'background Color 2',
	textColor1: 'Text Color 1',
	textColor2: 'Text Color 2',
	iconColor1: 'Icon Color 1',
	mainColorText: 'Main Color Text',
	statusBarColor: 'Status Bar Color',
	AcceptOrDeclineProudctNow: 'Accept or Decline Product Now',
	AltName: 'Name in Alternative Language',
	POS: "POS",
	Note: "Note",
	InvalidCouriers: "Invalid Couriers",
	Checkout: 'Checkout',
	MustSelectProducts: 'Please select products first',
	Drivers: "Drivers",
	NoContent: "No Content",
	DriverOrder: 'Driver Order',
	SelectLocation: 'Select Your Location',
	OrderLocation: 'Order Location',
	minDate: 'Minmum Date',
	maxDate: 'Maximum Date',
	HexColor: 'Hex Color',
	invaildColor: 'Please Enter Hex-Color Include #',
	HideAddToCart: 'Hide Add to Cart Button',
	NoShipping: 'No Shipping',
	SelectCountryFirst: "Select country first please",
	SelectCityFirst: "Select city first please",
	DriverRebort: 'Driver Report',
	TotalOrderCost: 'Total Order Cost',
	TotalDeliveryCost: 'Total Delivery Cost',
	TotalMins: 'Total Mins',
	CantSelectDriver: "Can't select this driver",
	UpdateOrderLocation: 'Update order location',
	OrderInbox: 'Order',
	CustomerInbox: 'Customer',
	Resources: "Resources",
	IsRequiredOnCheckOut: 'Is Required on Checkout',
	EnableOPtionGroupingInCheckout: 'Enable Option Grouping in Checkout',
	ShowInProducts: 'Show In Products',
	ChoosethelanguagetoDeleteitstranslation: 'Choose the Language to Delete Its Translation',
	CourierName: 'Default Courier Name',
	ShowProductsWithChildren: 'Show Products with Children',
	Collection: 'Collection',
	ExpiryInDays: 'Expiry in Days',
	MaxQtyPerDay: 'Max Quantity Per Day',
	QtyPerScan: 'Quantity Per Scan',
	QRCodeList: 'QR Code',
	QRCode: 'QR Code',
	OrderQRCode: 'Order QR Code',
	SaveToGallery: 'Save To Gallery',
	QRCodeGenerator: "QR Code Generator",
	IsGlobalInApp: 'Is Global in App',
	Required: 'Required',
	Optional: 'Optional',
	ShowInCheckOut: 'Show in Checkout',
	MustOneValueTrueShowInCheckOutShowInProducts: 'Must One Value True Show in Checkout Or Show In Products',
	YouShouldPutName: 'Please Enter the Name in This Language And Submit First',
	Options: 'Options',
	SignInDescription: 'Sign in Description',
	ChildrenCategory: 'Children Category',
	Latitude: 'Latitude',
	Longitude: 'Longitude',
	NotificationTemplates: 'Push Ads',
	NotificationTemplate: 'Notification Template',
	History: 'History',
	LastTimeSent: 'Last Time Sent',
	LastTimeSentQty: 'Last Time Sent Quantity',
	Body: 'Body',
	Cities: 'Cities',
	Areas: 'Areas',
	CustomerStatuses: 'Customer Statuses',
	CustomerTypes: 'Customer Types',
	NotifcationHassBeenSend: 'Notification has been sent',
	New: "New",
	FailedLocation: "Failed to fetch your location. Please check app permissions",
	Filter1: 'Filter 1:',
	Filter2: 'Filter 2:',
	Navigation: 'Navigation',
	AM: "AM",
	PM: "PM",
	isreplaceableDescription: 'is replaceable Description',
	CancelOrder: 'Cancel Order',
	OrderCancled: 'Order Canceled',
	UserInbox: 'User',
	Free: 'Free',
	MaxFreeProductsPerSubStore: 'Max Free Products Per Sub-Store',
	MaxFreeProducts: 'Max Free Products',
	TimeBetweenFreeProducts: 'Time Between Free Products',
	TimeBetweenFreeProductsPerSubStore: 'Time Between Free Products Per Sub-Store',
	ValidatyFromApplyInDays: 'Validaty From Apply In Days',
	FreeProducts: 'Free Products',
	Image: 'Image',
	File: 'File',
	ShowInMap: 'Show in Map',
	Reminder: 'Reminder',
	QuickReminder: 'Quick Reminder:',
	AfterHourse: 'After Hours:',
	At: 'At:',
	Dayes: 'Days',
	Week: 'Week',
	Day: 'Day',
	After: 'After',
	Message: 'Message:',
	pleasePutAtLeastAtTimeOrAfterHoures: 'please Put At-Time Or After-Hours',
	Key5: 'Key 5',
	Key6: 'Key 6',
	Key7: 'Key 7',
	Key8: 'Key 8',
	Key9: 'Key 9',
	Key10: 'Key 10',
	Key11: 'Key 11',
	Key12: 'Key 12',
	Key13: 'Key 13',
	SubStoreLocation: 'Sub-Store Location',
	TimeZone: 'Time Zone',
	ManagePlaces: 'Manage Places',
	YouMustSelectCountry: 'You Must Select Country',
	YouMustSelectAtLeastOneCity: 'You Must Select At Least One City',
	YouMustSelectAtLeastOneArea: 'You Must Select At Least One Area',
	VirtualBalance: 'Virtual Balance',
	Stock: 'Stock',
	Camera: 'Camera',
	Library: 'Library',
	MainLanguage: 'Main Language',
	SecondLanguage: 'Second Language',
	UpdateProduct: 'Update Product',
	CreateCategory: 'Create Category',
	SimpleFile: 'Sample Excel File',
	Upload: 'Upload',
	ImportProductText: "Please make sure the attached Zip file contains Excel file and product images at the root of it. Note: review the data before submitting as this action is irreversible",
	Config: 'Config',
	Import: 'Import',
	selectZipFile: 'Select Zip File',
	ImportProductsCatrgories: 'Import Products',
	ImportArea: 'Import Area',
	UpdateVirtualMoney: 'Update Virtual Money',
	Update: 'Update',
	All: 'All',
	CustomerOrderCount: '#Customer Order:',
	CustomerTotalSpent: 'Customer Spent:',
	Customeroperations: 'Customer Operations',
	Full: 'Full',
	TermsAndCondation: 'By Using This App I Already Approve Terms Of Condition And Privacy Policy',
	Processing: 'Processing',
	Pendding: 'Pendding',
	AddedToCart: 'Added To Cart',
	AddToCard: 'Add To Card',
	OrderNote: 'Note : ',
	UnKnownBrand: 'Un Known Brand : ',
	Copied: 'Copied',
	HashOrderCode: '#Order Code',
	TwoPushnotificaitonhavebeensent: 'Two Push notificaiton have been sent',
	TestNotification: 'Test Notification',
	PriceChange: 'Price Change',
	POS_OptionGroups: 'Option Groups',
	POS_ShowDriver: 'Show Driver',
	POS_IsDriverRequired: 'Is Driver Required',
	POS_ShowSubStore: 'Show Sub Store',
	POS_IsSubStoreRequired: 'Is SubStore Required',
	POS_ShowCountry: 'Show Country',
	POS_IsCountryRequired: 'Is Country Required',
	POS_ShowCity: 'Show City',
	POS_IsCityRequired: 'Is City Required',
	POS_ShowArea: 'Show Area',
	POS_IsAreaRequired: 'Is Area Required',
	POS_ShowAddress: 'Show Address',
	POS_IsAddressRequired: 'Is Address Required',
	POS_ShowOrderStatus: 'Show Order Status',
	POS_DefaultOrderStatus: 'Default Order Status',
	SelectCourier: 'Select Courier :',
	Cart: 'Cart',
	SelectOptions: 'SelectOptions : ',
	PlaceOrder: 'Place Order',
	SomeThingWrongCheckThePERMISSIONS: 'Check Connection And App Permissions',
	DownloadInvoice: 'Download Invoice',
	NoteForOrder: 'Note : ',
	HtmlDescription: 'Html Description',
	IncludeInSideMenu: 'Include In Side Menu',
	IncludeInNavBar: 'Include In Nav Bar ',
	IsShowInHomePage: 'Is Show In Home Page',
	IsShowInHomePageOrder: 'Is Show In Home Page Order',
	ShareInvoice: 'Share Invoice',
	IsDraft: 'Is Draft',
	ToProductOption: 'ToProductOption',
	MyApp: 'My App',
	OneLink: 'One Link',
	Android: 'Android',
	iOS: 'iOS',
	CantOpenRightNow: 'Cant Open Right Now',
	CantCopyRightNow: 'Cant Copy Righ tNow',
	InHomePageMaxHieght: 'In Home Page Max Height',
	InHomePageMaxWidth: 'In Home Page Max Width',
	ShowWareHouse: 'Show Wareاouses',
	IsAddressRequired: 'Is Address Required',
	TenantDescription: 'Best store in your area',
	AFFCode: 'AFF Code',
	Affiliate: 'Affiliate',
	AffiliateRoles: 'Affiliate Roles',
	AffiliateRole: 'Affiliate Role',
	ForMe: 'For Me',
	ForNewCustomer: 'For New Customer',
	MinStep: 'Min Step',
	MaxStep: 'Max Step',
	MinStepShouldBeANumber: 'MinStep Should Be A Number',
	MaxStepShouldBeANumber: 'MaxStep Should Be A Number',
	MinStepShouldBeGreaterThanOne: 'MinStep Should Be Greater Than One',
	MaxStepShouldBeGreaterThanMinStep: 'MaxStep Should Be Greater Than MinStep',
	ForMeShouldBeAPositiveNumber: 'For Me Should Be A Positive Number',
	ForNewCustomerShouldBeAPositiveNumber: 'For New Customer Should Be A Positive Number',
	ItemCount: '#total : ',
	ExtraPrice: 'Extra Price',
	ShowProducts: 'Show Products',
	EditDescription: 'Edit Description',
	DefaultCountry: 'Default Country',
	DefaultCity: 'Default City',
	DefaultArea: 'Default Area',
	TenantSettings: 'Settings',
	Reorder: 'Reorder',
	HomePageReorder: 'Home Page Reorder',
	AllowMultiple: 'Allow Multiple',
	DefaultLocation: 'Default Location',
	SellHours: 'Sell Hours',
	Available24Hours: 'Available 24 Hours',
	Is24Hours: '24 Hours ?',
	ErrorMessage: 'Error Message',
	OrderMinValue: 'Order Min Value',
	OrderMaxValue: 'Order Max Value',
	FreeShippingAbove: 'Free Shipping Above',
	SetTypeSettings: 'Set Type Settings',
	SubStoreTypes: 'SubStore Types',
	SubStoreType: 'SubStore Type',
	NameCantBeEmpty: 'Name Can\'t Be Empty',
	MaxProductsCount: 'Max Products Count',
	MaxProductsCountShouldBeAPositiveNumber: 'Max Products Count Should Be A Positive Number',
	SetAsDefault: 'Set As Default',
	TypeCantBeEmpty: 'Type Can\'t Be Empty',
	ShownInCustomer: 'Shown In Customer',
	EstimatedDeliveryTime: 'Estimated Delivery Time',
	UpdateDate: 'Update Date',
	CreateDate: 'Create Date',
	DeliveryDate: 'Delivery Date',
	SKU: 'SKU',
	StatusHistory: 'Status History',
	AltName: 'Alt Name',
	ProccessingFees: 'Proccessing Fees',
	ImportProducts: 'Import Products',
	UpdatePricesAndStock: 'Update Prices And Stock',
	DownloadExcelFile: 'Download Excel File',
	UploadExcelFile: 'Upload Excel File',
	SelectXlsxFile: 'select xlsx File',
	MinOrderValue: 'Min Order Value',
	PopUps: 'PopUps',
	PopUp: 'PopUp',
	Where: 'Where',
	NoNavigation: 'No Navigation',
	//PopUpWhere
	IsPopUp: 'Is Pop Up',
	ShowTop: 'Show Top',
	ShowMiddle: 'Show Middle',
	ShowBottom: 'Show Bottom',
	ShowOnlyOnce: 'Show Only Once',
	ShowOnlyOnceAfterNavigate: 'Show Only Once After Navigate',
	HomePageTopSlider: 'Home Page Top Slider',
	HomePageAds1: 'Home Page Ads1',
	HomePageAds2: 'Home Page Ads2',
	HomePageAds3: 'Home Page Ads3',
	ShowInSearch: 'Show In Search',
	ShowInCheckout: 'Show In Checkout',
	ShowInCart: 'Show In Cart',
	ShowInProfile: 'Show In Profile',
	ShowInAllCats: 'Show In All Cats',
	ShowInAllProducts: 'Show In All Products',
	ShowInOrders: 'Show In Orders',
	ShowInOrder: 'Show In Order',
	ShowInFlashOffers: 'Show In Flash Offers',
	ShowInMonthlyOffers: 'Show In Monthly Offers',
	ShowInWishLists: 'Show In WishLists',
	ShowInMostLikes: 'Show In Most Likes',
	ShowInSubstores: 'Show In Substores',
	ShowInFavouriteSubsTores: 'Show In Favourite Substores',
	//PopUpWhere Finish
	GoLivee: 'Go Live',
	ShareProduct: 'Share Product',
	Url: 'Url',
	CantBeEmpty: ' Can\'t Be Empty',
	Source: 'Source',
	ValidityInDays: 'Validity In Days',
	ShouldBeAPositiveNumber: ' Should Be A Positive Number',
	ValidityExtendRejected: 'Validity Extend Rejected',
	ValidityExtendAccepted: 'Validity Extend Accepted',
	ExtendRequest: 'Extend Request',
	ExtendFor: 'Extend For',
	ExpirationDate: 'Expiration Date',
	ShowQrCodeReader: 'Show QR Code Reader In Customer App Side Menu',
	UniquePermission: 'Unique Permission',
	Commission: 'Commission',
	Spend: 'Spend Value',
	OrderedBefore: 'Ordered Before',
	NotOrderedBefore: 'Not Ordered Before',
	CustomerApp: 'Customer App',
	Filter: 'Filter',
	Sort: 'Sort',
	SalesHigherFirst: 'Sales (Higher First)',
	SalesLowerFirst: 'Sales (Lower First)',
	MostViews: 'Most Views',
	PriceHigherFirst: 'Price (Higher first)',
	PriceLowerFirst: 'Price (Lower First)',
	WhatsappAlert: 'Please Install Whatsapp To Send Direct Messages Via Whatsapp',
	PhoneAlert: 'Phone Number Is Not Available',
	SetQty: 'Set Quantity',
	OrdersStatus: 'Order Status',
	OrdersStatuses: 'Orders Statuses',
	OrderStatus: 'Order Status',
	ShownInCustomerList: 'Shown In Customer List',
	StandardOrderCycle: 'Standard Order Cycle',
	CantBeDeleted: 'Can\'t Be Deleted',
	ImageSizeError: 'The Image Size Must Be More Than or Equal 700 * 700',
	ImageDimensionsError: 'Image Width Should Be Equal To Image Height',
};
//!!!!!!!! KEY END !!!!!!!!

//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const ar = {
	Filter: 'تصفية',
	CustomerApp: 'تطبيق الزبون',
	NotOrderedBefore: 'لم يطلب من قبل',
	OrderedBefore: 'طلب من قبل',
	Spend: 'قيمة الإنفاق',
	Commission: 'عمولة',
	UniquePermission: 'إذن وحيد',
	ShowQrCodeReader: 'إظهار قارئ كود الاستجابة السريعة في القائمة الجانبية لتطبيق العميل',
	ExpirationDate: 'تاريخ الإنتهاء',
	ExtendFor: 'تمديد ل',
	ExtendRequest: 'طلب تمديد',
	ValidityExtendAccepted: 'تم تمديد الصلاحية',
	ValidityExtendRejected: 'تم رفض تمديد الصلاحية',
	ShouldBeAPositiveNumber: ' يجب أن يكون رقمًا إيجابيًا',
	ValidityInDays: 'الصلاحية في أيام',
	Source: 'المصدر',
	CantBeEmpty: 'لا يمكن أن يكون فارغًا ',
	InvalidURL: "الرابط غير صالح",
	Url: 'رابط',
	ShareProduct: 'مشاركة المنتج',
	//PopUpWhere Start
	IsPopUp: 'هل نافذة منبثقة',
	ShowTop: 'إظهار في الأعلى',
	ShowMiddle: 'إظهار في الوسط',
	ShowBottom: 'إظهار في الأسفل',
	ShowOnlyOnce: 'إظهار مرة واحدة فقط ',
	ShowOnlyOnceAfterNavigate: 'إظهار مرة واحدة فقط بعد التنقل',
	HomePageTopSlider: 'المتزلج الاعلي في الصفحة الرئيسية',
	HomePageAds1: 'الاعلانات الاولي في الصفحة الرئيسية',
	HomePageAds2: 'الاعلانات الثانية في الصفحة الرئيسية',
	HomePageAds3: 'الاعلانات الثالثة في الصفحة الرئيسية',
	ShowInSearch: 'إظهار في البحث',
	ShowInCheckout: 'إظهار في الدفع',
	ShowInCart: 'إظهار في السلة',
	ShowInProfile: 'إظهار في الصفحة الرئيسية',
	ShowInAllCats: 'إظهار في كل الأقسام',
	TermsAndCondation: 'باستخدام هذا التطبيق ، لقد وافقت بالفعل على الشروط والأحكام وسياسة الخصوصية',
	ShowInAllProducts: 'إظهار في كل المنتجات',
	ShowInOrders: 'إظهار في الطلبات',
	ShowInOrder: 'إظهار في الطلب',
	ShowInFlashOffers: 'إظهار في العروض السريعة',
	ShowInMonthlyOffers: 'إظهار في العروض الشهرية',
	ShowInWishLists: 'إظهار في المنتجات المفضلة',
	ShowInMostLikes: 'إظهار في الاكثر اعجابا',
	ShowInSubstores: 'إظهار في المتاجر الفرعية',
	ShowInFavouriteSubsTores: 'إظهار في المتاجر الفرعية المفضلة',
	//PopUpWhere Finish
	NoNavigation: 'لا تنقل',
	Where: 'اين',
	PopUp: 'النافذة المنبثقة',
	PopUps: 'النوافذ المنبثقة',
	GoLivee: 'رفع التطبيق',
	MinOrderValue: 'أقل قيمة للطلب',
	SelectXlsxFile: 'اختار ملف xlsx',
	UploadExcelFile: 'تحديث ملف اكسل',
	DownloadExcelFile: 'تحميل ملف اكسل',
	UpdatePricesAndStock: 'تحديث الأسعار والأوراق المالية',
	ImportProducts: 'استيراد المنتجات',
	AltName: 'اسم بديل',
	ProccessingFees: 'رسوم المعالجة',
	StatusHistory: 'تاريخ الحالة',
	SKU: 'SKU',
	DeliveryDate: 'تاريخ التسليم',
	CreateDate: 'تاريخ الإنشاء',
	UpdateDate: 'تحديث التاريخ',
	EstimatedDeliveryTime: 'وقت التسليم المقدر',
	ShownInCustomer: 'يظهر للعملاء',
	TypeCantBeEmpty: 'النوع لا يمكن أن يكون فارغًا',
	SetAsDefault: 'تعيين كافتراضي',
	MaxProductsCountShouldBeAPositiveNumber: 'الحد الأقصى لعدد المنتجات يجب أن يكون رقمًا إيجابيًا',
	MaxProductsCount: 'العدد الأقصى للمنتجات',
	NameCantBeEmpty: 'الاسم لا يمكن أن يكون فارغًا',
	SubStoreTypes: 'نوع المتجر الفرعي',
	SubStoreTypes: 'أنواع المتاجر الفرعية',
	SetTypeSettings: 'ضبط إعدادات النوع',
	OrderMinValue: 'الحد الأدنى للقيمة للطلب',
	OrderMaxValue: 'الحد الأقصى للقيمة للطلب',
	FreeShippingAbove: 'شحن مجاني للأعلي من',
	ErrorMessage: 'رسالة الخطأ',
	Is24Hours: '٢٤ ساعة ؟',
	Available24Hours: 'متاح ٢٤ ساعة',
	SellHours: 'ساعات البيع',
	DefaultLocation: 'الموقع الافتراضي',
	Reorder: 'ترتيب',
	HomePageReorder: 'ترتيب الصفحة الرئيسية',
	AllowMultiple: 'السماح بالتعدد',
	TenantSettings: 'الاعدادات',
	DefaultArea: 'المنطقة الافتراضية',
	DefaultCity: 'المدينة الافتراضية',
	DefaultCountry: 'البلد الافتراضية',
	EditDescription: 'تعديل الوصف',
	ItemCount: '#الاجمالي : ',
	ShowProducts: 'إظهار المنتجات',
	ForNewCustomerShouldBeAPositiveNumber: 'للعميل الجديد يجب أن يكون رقمًا إيجابيًا',
	ForMeShouldBeAPositiveNumber: 'لي يجب أن يكون رقمًا إيجابيًا',
	MaxStepShouldBeGreaterThanMinStep: 'يجب أن يكون الحد الأقصي أكبر من الحد الأدنى ',
	MinStepShouldBeGreaterThanOne: 'الحد الأدنى يجب أن يكون أكبر من واحد',
	MaxStepShouldBeANumber: 'يجب أن يكون الحد الأقصي رقمًا',
	MinStepShouldBeANumber: 'يجب أن يكون الحد الأدنى رقمًا',
	MaxStep: 'الحد الأقصى',
	MinStep: 'الحد الأدنى',
	ForNewCustomer: 'للعميل الجديد',
	ForMe: 'لي',
	AffiliateRole: 'دور تابع',
	AffiliateRoles: 'ادوار تابعة',
	ExtraPrice: 'تسعيره اضافية',
	Affiliate: 'انضم',
	AFFCode: 'AFF كود',
	TenantDescription: 'افضل متجر الكتروني',
	IsAddressRequired: 'العنوان مطلوب',
	ShowWareHouse: 'عرض المستودعات',
	InHomePageMaxHieght: 'الصفحة الرئيسية اعلي ارتفاع',
	InHomePageMaxWidth: 'الصفعة الرئيسية اعلي عرض',
	CantCopyRightNow: 'لا يمكن النسخ الان',
	CantOpenRightNow: 'لا يمكن الفتح الان',
	iOS: 'اي او اس',
	Android: 'اندرويد',
	OneLink: 'رابط واحد',
	MyApp: 'تطبيقي',
	ToProductOption: 'الي خيار',
	IsDraft: 'محذوف ؟',
	ShareInvoice: 'مشاركة الفاتورة',
	IsShowInHomePageOrder: 'ترتيبة في الصفحة الرئيسية',
	IsShowInHomePage: 'اظهار في الصفحة الرئيسية',
	IncludeInNavBar: 'اضافة الي تابات التنقل',
	IncludeInSideMenu: 'اضافة الي قاءمة الجانب',
	HtmlDescription: 'وصف ب html',
	NoteForOrder: 'ملاحظة : ',
	DownloadInvoice: 'تحميل الفاتورة',
	SomeThingWrongCheckThePERMISSIONS: 'افحص الاتصال وصلاحية التطبيق من الاعدادات',
	PlaceOrder: 'ارسال الطلب',
	SelectOptions: 'اختار الخيارات : ',
	Cart: 'السلة',
	SelectCourier: 'اختار شركة الشحن :',
	POS_OptionGroups: 'مجموعات الخيارات ',
	POS_ShowDriver: 'اظهار الموصل ',
	POS_IsDriverRequired: 'الموصل اجباري ',
	POS_ShowSubStore: 'اظهار الفرع',
	POS_IsSubStoreRequired: 'الفرع اجباري',
	POS_ShowCountry: 'اظهار البلد ',
	POS_IsCountryRequired: 'البلد اجباري',
	POS_ShowCity: 'اظهار المدينة',
	POS_IsCityRequired: 'المدينة اجباري',
	POS_ShowArea: 'اظهار المنطقة',
	POS_IsAreaRequired: 'المنطقة اجبارية',
	POS_ShowAddress: 'اظهار العنوان',
	POS_IsAddressRequired: 'العنوان اجباري',
	POS_ShowOrderStatus: 'اظهار حالة الطلب',
	POS_DefaultOrderStatus: 'حالة الطلب الافتراضية',
	PriceChange: 'تغير السعر',
	TestNotification: 'اختبار الاشعار',
	TwoPushnotificaitonhavebeensent: 'تم ارسال اشعارين الى جهازك',
	HashOrderCode: '#كود الطلب',
	Copied: 'تم النسخ',
	UnKnownBrand: 'علامة تجارية غير معروفة : ',
	OrderNote: 'ملاحظة : ',
	AddToCard: 'اضف الي السلة',
	AddedToCart: 'انضافة الي السلة',
	Pendding: 'قيد الانتظار',
	Processing: 'معاملة',
	Full: 'الكل',
	Customeroperations: 'عمليات العيل',
	CustomerTotalSpent: 'اجمالي انفاق العميل:',
	CustomerOrderCount: '#طلبات العميل:',
	All: 'الكل',
	Update: 'تحديث',
	UpdateVirtualMoney: 'تحديث النقود الافتراضية',
	ImportArea: 'رفق الملفات',
	ImportProductsCatrgories: 'رفق منتج',
	selectZipFile: 'اختار ملف zip',
	Import: 'رفق ملف',
	Config: 'اعداد',
	ImportProductText: 'يرجى التأكد من الملف المضغوط المرفق الذي يحتوي على ملف اكسل وصور المنتج في جذر الملف المضغوط ، تحقق مرة أخرى من البيانات ويرجى ملاحظة أن الناتج غير قابل للعكس',
	Upload: 'رفع',
	SimpleFile: 'ملف اكسل مثال',
	CreateCategory: 'انشاء فئة',
	UpdateProduct: 'تحديث المنتج',
	SecondLanguage: 'االغة الثانية',
	MainLanguage: 'اللغة الرئيسية',
	Library: 'المكتبة',
	Camera: 'كامير',
	VirtualBalance: 'الرصيد الظاهري',
	Stock: 'مخزن',
	YouMustSelectAtLeastOneArea: 'يجب اختيار منطقة واحدة على الاقل',
	YouMustSelectAtLeastOneCity: 'يجب اختيار مدينة واحدة على الاقل',
	YouMustSelectCountry: 'يجب اختيار بلد واحد على الاقل',
	ManagePlaces: 'ادارة الأماكن',
	TimeZone: 'توقيت المنطقة',
	SubStoreLocation: 'موقع الفرع',
	Key5: 'مفتاح 5',
	Key6: 'مفتاح 6',
	Key7: 'مفتاح 7',
	Key8: 'مفتاح 8',
	Key9: 'مفتاح 9',
	Key10: 'مفتاح 10',
	Key11: 'مفتاح 11',
	Key12: 'مفتاح 12',
	Key13: 'مفتاح 13',
	pleasePutAtLeastAtTimeOrAfterHoures: 'ضع الوقت او اختر ميعاد!',
	Message: 'الرسالة:',
	After: 'بعد',
	Day: 'يوم',
	Week: 'اسبوع',
	Dayes: 'أيام',
	At: 'في :',
	AfterHourse: 'بعد ساعات:',
	QuickReminder: 'تنبيه سريع:',
	Reminder: 'تنبيه',
	ShowInMap: 'عرض في الخريطة',
	File: 'ملف',
	Image: 'صورة',
	FreeProducts: 'منتجات مجانية',
	ValidatyFromApplyInDays: 'الصلاحية من تاريخ التفعيل بالأيام',
	TimeBetweenFreeProductsPerSubStore: 'الوقت بين المنتجات المجانية للمحل',
	TimeBetweenFreeProducts: 'الوقت بين المنتجات المجانية',
	MaxFreeProducts: 'اقصي عدد المنتجات المجانية',
	MaxFreeProductsPerSubStore: 'اقصي عدد المنتجات المجانية للمحل',
	Free: 'مجانا',
	UserInbox: 'مستخدم',
	OrderCancled: 'تم الغاء الطلب',
	CancelOrder: 'الغاء الطلب',
	isreplaceableDescription: 'وصف متغير ؟ ',
	AM: "صباحا",
	PM: "مساء",
	Navigation: 'تنقل الي',
	Filter2: 'فلتر 2:',
	Filter1: 'فلتر 2:',
	FailedLocation: "لم نتمكن من التعرف على موقعك. من فضلك قم بفحص صلاحيات التطبيق",
	New: "جديد",
	NotifcationHassBeenSend: 'تم ارسال الاشعار',
	CustomerTypes: 'انواع الزبائن',
	CustomerStatuses: 'حالات الزبائن',
	Areas: 'المناطق',
	Cities: 'المدن',
	Body: 'المحتوي',
	LastTimeSentQty: 'كمية اخر وقت تم الارسال فيها',
	LastTimeSent: 'اخر وقت تم الارسال فيه ',
	History: 'التاريخ',
	NotificationTemplate: 'قالب الاشعارات',
	NotificationTemplates: 'اشعارات مباشرة',
	Longitude: 'خط الطول',
	Latitude: 'خط العرض',
	ChildrenCategory: 'الفئة الابن',
	SignInDescription: 'وصف للتسجيل',
	Options: 'الخيارات',
	YouShouldPutName: 'من فضلك ادخل الاسم بهذه اللغة و قم بالضغط علي زر الارسال اعلي الشاشة اولا',
	MustOneValueTrueShowInCheckOutShowInProducts: 'يجب ان تكون قيمة واحده مختاره عرض عند الدفع او عرض ف المنتج',
	ShowInCheckOut: 'عرض عند الدفع',
	Optional: 'اختياري',
	Required: 'اجباري',
	IsGlobalInApp: 'عموميا في التطبيق',
	QRCodeGenerator: "مولد رمز الاستجابة السريع",
	SaveToGallery: 'حفظ في معرض الصور',
	OrderQRCode: 'كود الطلب',
	QRCode: 'كو ال QR',
	QRCodeList: 'الكود',
	ExpiryInDays: 'ايام تاريخ الانتهاء',
	MaxQtyPerDay: 'الحد الاقصى للكمية لليوم',
	QtyPerScan: 'الكمية للفحص',
	Collection: 'مجموعة',
	ShowProductsWithChildren: 'اظهار المنتجات مع الفئات',
	CourierName: 'اسم شركة الشحن الافتراضي',
	ChoosethelanguagetoDeleteitstranslation: 'اختار اللغة لمسح ترجمتها',
	ShowInProducts: 'عرض ف المنتجات',
	EnableOPtionGroupingInCheckout: 'تمكين تجميع الخيارات ف الشراء',
	IsRequiredOnCheckOut: 'اجباري عند الشراء',
	Resources: "موارد",
	CustomerInbox: ' الزبائن',
	OrderInbox: ' الطلبات',
	UpdateOrderLocation: 'تحديث موقع الطلب',
	CantSelectDriver: "لا يمكنك اختيار هذا السائق",
	TotalMins: 'اجمالي الدقائق',
	TotalDeliveryCost: 'اجمالي تكلفة التوصيل',
	TotalOrderCost: 'اجمالي تكلفة المنتج',
	DriverRebort: 'تقرير الموصل',
	SelectCountryFirst: "من فضلك اختر البلد اولا",
	SelectCityFirst: "من فضلك اختر المدينة اولا",
	NoShipping: 'دون شحن',
	HideAddToCart: 'اخفاء اضافة الي العربة',
	invaildColor: 'من فضلك ادخل اللون hex مضاف الية #',
	HexColor: 'لون الهكس',
	maxDate: 'تاريخ الحد الاقصى',
	minDate: 'تاريخ الحد الادنى',
	OrderLocation: 'مكان الطلب',
	SelectLocation: 'اختار مكانك',
	DriverOrder: 'طلبات السائق',
	NoContent: "لا يوجد محتوى",
	Drivers: "السائقون",
	MustSelectProducts: 'من فضلك قم بتحديد المنتجات اولا',
	Checkout: 'الدفع',
	InvalidCouriers: "التوصيل غير صالح",
	Note: "ملحوظة",
	POS: "نقطة البيع",
	AltName: 'الاسم باللغة البديلة',
	AcceptOrDeclineProudctNow: 'قبول او رفض المنتج',
	bgColor1: 'لون الخلفية 1',
	bgColor2: 'لون الخلفية 2',
	textColor1: 'لون الخط 1',
	textColor2: 'لون الخط 2',
	iconColor1: 'لون الايقونة 1',
	mainColorText: 'اللون الرئيسي للخط',
	statusBarColor: 'لون شريط المهام',
	ProductQtyStep: 'خطوات الكمية',
	ProductMinQty: 'الحد الادنى للكمية',
	ProductMaxQty: 'الحد الاقصى للكمية',
	LessThanZero: 'القيمة لا يجب ان تكون اقل من الصفر',
	AcceptOrDeclineOrderNow: 'قبول او رفض الطلب الان',
	Accept: 'قبول',
	Decline: 'رفض',
	DeliverMap: 'الخريطة',
	WeDontHaveTheLatitudeAndLongtude: 'ليس لدينا خطوط الطول و دوائر العرض ',
	Analystic: 'تحليلات',
	TodayViews: 'مشاهدات اليوم',
	YesterdayViews: 'مشاهدات امس',
	ThisWeekViews: 'مشاهدات هذا الاسبوع',
	ThisMonthViews: 'مشاهدات هذا الشهر',
	Days30BeforeViews: 'مشاهدات قبل 30 يوم',
	Days7BeforeViews: 'مشاهدات قبل 7 ايام',
	Color4: 'لون 4',
	Color5: 'لون 5',
	Color6: 'لون 6',
	Color7: 'لون 7',
	Color8: 'لون 8',
	Color9: 'لون 9',
	Color10: 'لون 10',
	Send: 'ارسال',
	Notes: 'ملاحظات',
	assignTODriver: 'تمرير لسائق',
	AddNewForCustomer: '+ أضافة جديد',
	Store_Style: 'شكل المتجر',
	Store_Listing: 'قائمة المتجر',
	Shipping_Method: 'طريقة التسوق',
	Payment_Method: 'طريقة الدفع',
	Logo: 'الصورة',
	Config_Page: 'اعدادات الصفحات',
	TenProducts: '10 منتجات',
	TenCategory: '10 فئات',
	Store_Name: 'أسم المتجر',
	Brofite: 'الربح',
	Completed: 'انتهى',
	Info2: 'عند الانتهاء من ادخال جميع البيانات المطلوبة في هذه الصفحة, سوف يكون التطبيق الخاص بك متاح على متجر App Stores خلال اسبوعين من تاريخ اكمال ادخال البيانات الضرورية',
	GoLiveTitle: 'رفع التطبيق',
	GoLive: 'رفع التطبيق:',
	Intro: 'ارجو منك اكمال ادخال البيانات, الضرورية والازمة لنشر المتجر الخاص بك على App Store',
	IsDriver: 'سائق',
	Comission: 'عمولة',
	Saving: 'وفر',
	Porvider: 'المزود',
	AnswerNow: 'اجب',
	Pricechange: 'تغير السعر',
	notselected: 'غير محدد',
	Group: 'مجموعة',
	Member: 'جزء',
	ProductOption: 'خيارات المنتج',
	PleaseWait: 'من فضلك انتظر',
	IsRequired: 'اجباري؟',
	Driver: 'السائق',
	AddIcon: 'اضف ايقونة',
	Title: 'عنوان',
	AddProduct: 'اضافة منتج',
	Qty: 'الكمية',
	NewOrder: 'طلب جديد',
	GetPricing: 'التكلفة',
	ProviderKey1: 'مفتاح 1',
	ProviderKey2: 'مفتاح 2',
	ProviderKey3: 'مفتاح 3',
	ProviderKey4: 'مفتاح 4',
	FeesFixed: 'نسبة ثابتة',
	FeesPercentage: 'نسبة الرسوم',
	Payment_Config: 'اعدادات الدفع',
	Payment: 'الدفع',
	SubStore: 'محل',
	Defaultfont: 'الخط الافتراضي',
	dataReset: 'تم اعادة الضبط',
	MoreThanOne: 'يحب ان يكون اكتر من اختيار',
	Pages: 'الصفحات',
	FullName: 'الاسم بالكامل',
	Gps: 'تأكد من انك قمت بتفعيل الموقع وانك لديك اتصال بالأنترنت',
	AddWarehouse: 'اضافة مخزن',
	ShippingTypes: 'نوع التسوق',
	Warehouse: 'المستودع',
	GpsCheckin: 'فحص الموقع',
	BasicInfo: 'المعلومات الرئيسية',
	IsOpen: 'متاح ؟',
	From: 'من',
	To: 'الي',
	WorkingHours: 'مواعيد المستودع',
	Close: 'مغلق',
	Open: 'مفتوح',
	EnterCompanyName: 'ادخل اسم الشركة',
	AddressHasBeenSet: 'تم وضع العنوان كافتراضي',
	ShareAdress: 'مشاركة العنوان',
	SetDefault: 'جعلة المفترض',
	CompanyName: 'أسم الشركة',
	IsCompany: 'شركة؟',
	PostCode: 'كود البلد',
	Address2: 'بريد اليكتروني2',
	Address1: 'عنوان1 ',
	Email2: 'بريد الكتروني2 ',
	Email1: 'بريد الكتروني 1',
	SecondName: 'الاسم الثاني',
	DefaultLanguage: 'اللغة الافتراضية',
	Default: 'افتراضي',
	Adress: 'عنوان',
	Margin1: 'حافة 1',
	Margin2: 'حافة 2',
	Margin3: 'حافة 3',
	Padding3: 'محاذاة 3',
	Padding2: 'محاذاة 2',
	Padding1: 'محاذاة 1',
	BorderRadius: 'الزاوية',
	Sizes: 'المقاسات',
	UserThemeType: 'نوع وضع المستخدم',
	StoreThemeType: 'نوع وضع المتجر',
	AuthThemeType: 'نوع وضع المصادقة',
	FontType: 'نوع الخط',
	FontSize: 'حجم الخط',
	Color: 'اللون',
	Fonts: 'الخطوط',
	ThirdColor: 'اللون الثالث',
	SecondColor: 'اللون الثاني',
	MainColor: 'اللون الرئيسي',
	FontSizeValidation: 'حجم الخط يجب ان يكون اقل من 30 و اكثر من 10',
	StoreStyle: 'شكل المتجر',
	Theme: 'الوضع',
	LongDescription: 'الوصف الطويل',
	LabelNameCantbeleththan3charchter: 'الكلمة المتناسبة لا يجب ان تكون اقل من ثلاث احرف',
	ShortDescriptionCantbeleththan3charchter: 'الوصف القصير لا يجب ان يكون اقل من ثلاثون حرف',
	LongDescriptionCantbeleththan3charchter: 'الوصف الطويل لا يجب ان يكون اقل من ثلاثون حرف',
	NameOnStoreCantbeleththan3charchter: 'أسم المتجر لا يجب ان يكون اقل من تلات احرف',
	StoreList: 'قائمة المتجر',
	label: 'كلمة مناسبة',
	NOTIFICATIONS: 'الاشعارات',
	StoreListing: 'قائمة المتجر',
	Languages: 'اللغات',
	Profile: 'الصفحة الشخصية',
	StoreName: 'أسم المتجر',
	StoreProfile: 'صفحة المتجر',
	Width: 'عرض',
	cantdownload: 'لا يستطيع التحميل ',
	Visibility: 'الظهور',
	Demofile: 'ملف تجريبي',
	Question: 'سؤال',
	QuestionText: 'نص السؤال',
	Reviews: 'مراجعات',
	Questions: 'اسئلة',
	Text: 'النص',
	in1usd: 'للعملة الواحدة',
	Howmany: 'كم عدد',
	Product: 'المنتج',
	DataNotSaved: 'لم يتم الحفظ',
	SelectProductVisibility: 'اختار ظهور المنتج',
	SelectProductType: 'اختار نوع المنتج',
	RATINGRANAGE: 'نطاق التقييم',
	PriceRange: 'نطاق السعر',
	Etag: 'تاجات', // Put ETag Here 
	Category: 'الفئة',
	Enablequestions: 'تفعيل الاسئلة',
	Enablereviews: 'تفعيل المراجعات',
	Highstepmustbehigherthanlowstep: 'الخطوة العالية يلزم ان تكون اعلي من الخطوة المنخفضة',
	LowstepcantbelowerthanTwo: 'الخطوة المنخفضة لا يمكن ان تكون اقل من اثنان',
	Steppricevalue: 'السعر لا يمكن ان يكون فارغ ',
	Lowstepvaluecantbeempty: 'الخطوة المنخفضة لا يمكن ان تكون فارغة',
	Highstepvaluecantbeempty: 'الخطوة العالية لا يمكن ان تكون فارغة',
	pleaseenterarealprice: 'من فضلك ادخل السعر الحقيقي',
	pleaseenteraprice: 'من فضلك ادخل السعر ',
	ManufacturerPartNumber: 'رقم جزء الشركة المصنعة',
	LocalLocation: 'المكان المحلي',
	Weight: 'الوزن',
	Height: 'Height',
	nooptionsfound: 'لا يوجد خيارات',
	exceededfilesizelimit: 'مساحة الملف كبيرة',
	filetypenotsupported: 'صيغة الملف غير مدعومة ',
	Number: 'رقم',
	Numberofdaysdownloadavailable: 'عدد ايام التحميل المتاحة',
	Numberofdownloadsperday: 'عدد التحميلات ف اليوم',
	Media: 'ميديا',
	Files: 'ملفات',
	Physical: 'الهيئة',
	Pricing: "التسعير",
	selected: 'مختار',
	ParentCategory: 'أب الصنف ',
	SKU: 'يلزم ادخال SKU ',
	NegativeValidation: 'لا يجب ادخال قيمة سالبة',
	DateValidation: 'تاريخ البداية لا يمكن ان يكون اصغر من تاريخ النهاية ',
	DiscountPercentageValue: 'القيمة المئوية يلزم ان تكون اقل من او تساوي 100%',
	Login: 'تسجيل الدخول',
	SelectLanguage: 'اختار اللغة ',
	ResetPassword: 'استرجاع كلمة المرور',
	CantHaveEmptyInputs: 'من فضلك قم بملء كل المدخلات',
	InvalidEmail: 'البريد الالكتروني غير صالح',
	InvalidPhone: 'الجوال غير صالح',
	TooShortPassword: 'كلمة المرور قصيرة',
	Logout: 'تسجيل خروج',
	Email: 'البريد الالكتروني',
	Phone: 'الجوال',
	Password: 'كلمة المرور',
	ChangePassword: 'غير كلمة المرور',
	English: 'الانجليزية',
	Arabic: 'العربية',
	noInternet: "لا يوجد اتصال",
	connectionAvailable: "انترنت متاح",
	offlineNotice: "جهازك غير متصل بالإنترنت ، يرجى التأكد من أن اتصالك يعمل.",
	tryAgain: "حاول مرة أخري...",
	skip: "تخطي",
	Orders: "الطلبات",
	Order: "طلب",
	Products: "المنتجات",
	Inbox: "الواردة",
	Analytics: "تحليلات",
	More: "المزيد",
	Home: "الرئيسية",
	Back: "رجوع",
	InternalServerErrorTitle: "مشكلة بالخادم",
	InternalServerErrorBody: "مشكلة بالخادم. من فضلك حاول مرة اخرى لاحقا",
	NotFoundServerErrorTitle: "غير موجود",
	NotFoundServerErrorBody: "غير موجود. جرب شيء آخر",
	FloodServerErrorTitle: "إيقاف مؤقت",
	FloodServerErrorBody: "لا الإزعاج",
	ValidationServerErrorTitle: "مدخلات غير صحيحة",
	ValidationServerErrorBody: "مدخلات غير صحيحة. من فضلك تفحص ثم حاول مرة اخرى",
	LogicalServerErrorTitle: "غير ممكن",
	Notifications: "الاشعارات",


	WalkthroughBodyContent1: "متجرك الالكتروني في قبضة يدك",
	WalkthroughBodyContent2: "استمتع بمشاهدة متجرك ينمو",
	WalkthroughBodyContent3: "تحكم بطلبات عملائك بسرعة وسهولة",
	WalkthroughBodyContent4: "ارسل اشعارات لعملائك بجديدك من عروض او احداث جديدة بشكل مجاني",
	WalkthroughBodyContent5: "عدد لا محدود من المنتجات و الاقسام والخيارات ",
	WalkthroughBodyContent6: "تحكم في كل شيئ وفي اي وقت",
	WalkthroughBodyContent7: "احلم ثم خطط ثم جعله حقييقة",
	WalkthroughBodyContent8: "تحكم بجميع الصلاحيات كما يحلو لك",


	FailedLogin: "المستخدم غير موجود او كلمة المرور غير صحيحة",
	Sessions: "جلسات",
	Brands: "العلامات التجارية",
	Brand: "علامة تجارية",
	PleaseWait: "من فضلك انتظر",
	Categories: "الاقسام",
	Name: "اسم",
	FirstName: "الاسم الاول",
	LastName: "الاسم الثاني",
	ShortDescription: "وصف قصير",
	Description: "وصف",
	Website: "موقع إلكتروني",
	EditDescInEditor: "تعديل محتوى الوصف الطويل",
	RichTextEditor: "محرر النصوص",
	EditContentInEditor: "تعديل المحتوى",
	Editor: "تعديل",
	InvalidURL: "رابط غير صالح",
	ImageRequired: "الصورة مطلوبة",
	Translation: "الترجمة",
	dataSaved: "تم حفظ البيانات بنجاح!",
	Cancel: "الغاء",
	Confirm: "تأكيد",
	Search: "بحث",
	TranslationKey: "مفتاحية",
	SourceText: "نص المصدر",
	TargetText: "نص الهدف",
	Options: "خيارات",
	ProductOptions: "خيارات المنتج",
	ProductOptionsMembers: "أعضاء خيار المنتج",
	ProductOptionGroups: "مجموعات خيارات المنتج",
	AreYouSure: "هل انت متأكد؟",
	IconSelector: 'محدد الايقونات',
	Users: "المستخدمون",
	User: "المستخدم",
	MobileIcon: "أيقونة الموبايل",
	Members: "الأفراد",
	iconColor: "أيقونة / اللون",
	color: "اللون",
	Language: "اللغة",
	Info: "معلومات",
	Security: "الأمان",
	PersonalInfo: "معلومات شخصية",
	Permissions: "صلاحيات",
	Permission: "صلاحية",
	LoginHistory: "سجل تسجيل الدخول",
	LoginAccount: "حساب الدخول",
	Address1: "عنوان 1",
	Address2: "عنوان 2",
	CurrencyList: "قائمة العملات",
	SelectPlace: "اختر مكان",
	Country: "البلد",
	Countries: "البلاد",
	City: "المدينة",
	Area: "المنطقة",
	PassDontMatch: 'كلمة المرور غير مطابقة',
	ConfirmPassword: "تأكيد كلمة المرور",
	InvalidPasswordFormat: " كلمة المرور لازم تحتوى على حرف كبير و حرف صغير و حرف خاص و رقم",
	ETags: 'الكلمات الدلالية',
	ETag: 'الكلمة الدلالية',
	createNewetag: "إنشاء كلمة دلالية جديدة",
	NS_NewOrder: 'طلب جديد',
	NS_NewMessage: 'رسالة جديدة',
	NS_SecurityActions: 'الاحداث المتعلقة بالأمان',
	NS_Reviews: 'مراجعات',
	NS_Questions: 'اسئلة',
	NS_AskForPrice: 'سؤال عن السعر',
	NS_AutoDiscount: 'الاحداث المتعلقة بالتخفيضات التلقائية',
	NS_StatisticsAlert: 'احصائيات',
	Role: 'الدور',
	Warehouses: 'المستودعات',
	AddUser: 'إضافة مستخدم',
	Products: 'المنتجات',
	UserAlreadyExists: 'المستخدم موجود بالفعل',
	Customers: 'الزبائن',
	NoneSelected: 'غير محدد',
	Clear: 'مسح',
	Type: 'النوع',
	Status: 'الحالة',
	Address: 'العنوان',
	Store: 'المتجر',
	Stores: 'المتاجر',
	Statistics: 'احصائيات',
	VirtualMoney: 'نقود افتراضية',
	Spent: 'مُنفق',
	Gender: 'الجنس',
	Facebook: 'الفيسبوك',
	Twitter: 'التويتر',
	Birthday: 'يوم الميلاد',
	EnterConfirmCode: "من فضلك ادخل الكود التأكيدي الذى استلمته",
	IncorrectInput: 'مدخلات خاطئة',
	Roles: 'الادوار',
	MustHaveOneRole: 'يجب ان يتبقى على الاقل واحد',
	CanRead: 'قراءة',
	CanCreate: 'إضافة',
	CanEdit: 'تعديل',
	CanDelete: 'حذف',
	Delete: 'حذف',
	CanExport: 'تصدير',
	Discounts: 'خصومات',
	Filters: 'التصفية',
	Active: 'نشط',
	Inactive: 'غير نشط',
	Both: 'كلاهما',
	Customer: "الزبون",
	Courier: "التوصيل",
	Discount: "الخصم",
	Select: "اختر",
	ApplyFor: "يطبق على",
	Restriction: "حصر",
	CouponCode: "الكود",
	RequiresCouponCode: "يتطلب الكود",
	DiscountType: "نوع الخصم",
	DiscountLimitation: "حدود الخصم",
	LimitationTimes: "حدود الخصم",
	DiscountPercentage: "القيمة المئوية",
	DiscountAmount: "قيمة الخصم",
	MaximumDiscountAmount: "الحد الاقصى للخصم",
	ShowInWebsite: "عرض على التطبيق",
	StartDate: "تاريخ البداية",
	EndDate: "تاريخ النهاية",
	IsCumulative: "تراكمي",
	ApplyForChildCategory: "تشمل الاقسام الفرعية",
	SpentAmountRestriction: "الكمية المنفقة",
	Shipping: "الشحن",
	CouponCodeDuplicated: "كود الكوبون مكرر",
	Articles: "المقالات",
	Article: "مقال",
	ParentArticle: "المقال الام",
	Icon: "ايقونة",
	Stories: "القصص",
	Story: "قصة",
	Hours: "ساعة",
	Days: "ايام",
	Weeks: "اسبوع",
	Length: "الطول",
	Likes: "إعجابات",
	Views: "مشاهدات",
	TextColor: "لون النص",
	BackgroundColor: "لون الخلفية",
	Summary: "الملخص",
	Items: "اصناف",
	Item: "صنف",
	TrackingHistory: "تتبع",
	Chat: "محادثة",
	SubTotal: 'حاصل الجمع',
	Tax: "ضريبة",
	Total: "الإجمالي",
	Details: "التفاصيل",
	CreatedDate: "تاريخ الإنشاء",
	DeliveredDate: "تاريخ التوصيل",
	OrderCode: "كود الطلب",
	Save: 'حفظ',
	Advance_Settings: 'اعدادات متقدمة',
	Settings: 'الاعدادات',
	Courier_Config: 'اعدادات التوصيل',
	Courier: 'التوصيل',
	AdvanceSettings: 'اعدادات متقدمة',
	Price: "السعر",
	RealPrice: "السعر الحقيقي",
	SalePrice: "السعر المخفض",
	SaleExpirationDate: "تاريخ انتهاء التخفيض",
	MaxPurchaseCount: "الحد الأقصى لعدد المشتريات",
	Purchasefile: 'ملف الشراء',
	Currency: "العملة",
	priceSteps: "خطوات السعر",
	PricingHistory: "سجل التسعير",
	Tags: 'علامات',
	TypeNewTagHere: 'اكتب علامة جديدة هنا',
	LowStep: "خطوة منخفضة",
	HighStep: "خطوة عالية",
	Add: "إضافة",
	UpdateCost: "تحديث التكلفة",
	Where_Houses: 'مستودع',
	Shoping_Speed: 'سرعة الشحن',
	Quantity: "الكمية",
	Change: "تغيير",
	FixedPrice: "سعر ثابت",
	KgPrice: "سعر الكيلو جرام",
	Key1: "مفتاح 1",
	Key2: "مفتاح 2",
	Key3: "مفتاح 3",
	Key4: "مفتاح 4",
	SecurityKey: "مفتاح الامان",
	HavePutOneKey: 'ادخل علي الاقل مفتاح',
	PleaceSelectCites: ' اختار المدن',
	PleaceEnterKgPrice: ' ادخل سعر الكيلو جرام',
	ToCity: 'الي مدينة',
	ToArea: 'الى منطقة',
	FromCity: 'من مدينة',
	ToCountry: 'الي بلاد',
	FromCountry: 'من بلاد',
	PleaceEnterFixedPrice: 'ادخل السعر الثابت ',
	PleaceSelectWherehouse: 'اختار المخزن',
	PleaceSelectShoppingspeed: 'اختار سرعة الشحن',
	ExtraDetails: "تفاصيل اضافية",
	DoneSuccessfully: "تم بنجاح",
	Soon: "قريبا",
	SeeMore: "عرض المزيد",
	SeeLess: "عرض اقل",
	CustomerType: 'نوع الزبون',
	SelectCategory: 'اختر الفئة',
	overwrite: 'اعادة الكتابة',
	Done: 'تم',
	Images: 'الصور',
	isreplaceableimage: 'صوره متغيرة ؟',
	AdminTranslation: "ترجمة المدير",
	AppTranslation: "ترجمة التطبيق",
	SendAnswers: 'أرسال',
	Answer: 'اكتب اجابة',
	AnswerSended: 'اجابتك ارسلت',
	Answers: 'الاجابات',
	Approved: 'موافق',
	NotApproved: 'غير موافق',
	Replied: 'رد',
	NotReplied: 'لم يرد',
	NoFilter: 'بدون تصفية',
	ReviewDate: 'تاريخ المراجعة',
	ApproveDate: 'تاريخ الموافقة',
	OrderReview: 'عرض الطلبات',
	OrderId: 'رقم الطلب',
	Reply: 'رد',
	ReplyText: 'نص الرد',
	dataDeleted: 'تم المسح بنجاح ',
	Location: "الموقع",
	Rating: "التقييم",
	Sort: 'ترتيب',
	SalesHigherFirst: 'المبيعات (الأعلى أولاً)',
	SalesLowerFirst: 'المبيعات (الأدنى أولاً)',
	MostViews: 'الأكثر مشاهدة',
	PriceHigherFirst: 'السعر (الأعلى أولاً)',
	PriceLowerFirst: 'السعر (الأدنى أولاً)',
	WhatsappAlert: 'يرجى تثبيت واتساب لإرسال رسائل مباشرة عبر واتساب',
	PhoneAlert: 'رقم الهاتف غير متوفر',
	SetQty: 'حدد الكمية',
	OrdersStatus: 'حالة الطلب',
	OrdersStatuses: 'حالات الطلبات',
	OrderStatus: 'حالة الطلب',
	ShownInCustomerList: 'معروض في قائمة العملاء',
	StandardOrderCycle: 'دورة الترتيب القياسية',
	CantBeDeleted: 'لا يمكن الحذف',
	ImageSizeError: 'يجب أن يكون حجم الصورة أكبر من أو يساوي ٧٠٠ * ٧٠٠',
	ImageDimensionsError: 'يجب أن يكون عرض الصورة مساويًا لارتفاع الصورة',
};
//!!!!!!!! KEY END !!!!!!!!

//Don't change comment below, it's used by builder
//!!!!!!!! KEY START !!!!!!!!
export const fr = {
	Login: "Connecter",
	CantHaveEmptyInputs: "Veuillez remplire toutes les données",
	InvalidEmail: "Email Invalid",
	InvalidPhone: "Numéro invalid",
	TooShortPassword: "Mot de passe trop court",
	Signup: "Déconecter",
	Logout: "Déconecter",
	Email: "Email",
	Phone: "Téléphone",
	Password: "mot de passe",
	ChangePassword: "Changer de mot de passe",
	English: "Anglais",
	Arabic: "Arabe",
	noInternet: "Pas d'internet",
	connectionAvailable: "connexion disponible",
	offlineNotice: "Votre appareil n'est pas connecter a internet, verifier votre connexion",
	tryAgain: "Réessayer",
	skip: "Echapper",
	Orders: "Achats",
	Order: "Acheter",
	Products: "Produits",
	Inbox: "Boit de reception",
	Analytics: "Analyses",
	More: "Plus",
	Home: "Acceuil",
	Back: "Retour",
	Files: "Fichiers",
	InternalServerErrorTitle: "Problemes de serveur",
	InternalServerErrorBody: "Problemes de serveur veuillez reessayer plus tard",
	NotFoundServerErrorTitle: "Non trouver",
	NotFoundServerErrorBody: "Données non trouver veuillez réessayer autre chose",
	FloodServerErrorTitle: "Temporairement blocker",
	FloodServerErrorBody: "pas de spam",
	ValidationServerErrorTitle: "Données incorect",
	ValidationServerErrorBody: "Données incorecct, réessayer",
	LogicalServerErrorTitle: "ne peut faire ca ",
	Notifications: "Notifications",
	WalkthroughBodyContent1: "Enjoy watching your store growing",
	WalkthroughBodyContent2: "Donnez la permission à vos employés facilement",
	WalkthroughBodyContent3: "Guider vôtres clients a vous via GPS",
	WalkthroughBodyContent4: "Notifier vos clients avec des annonces de gratuitées",
	FailedLogin: "utilisateur non trouver ou mot de passe incorrect",
	Sessions: "Sessions",
	Brands: "Marques",
	Brand: "Marque",
	PleaseWait: "Veuillez patienter",
	Categories: "Categories",
	Name: "Nomer",
	FirstName: "Prénom",
	LastName: "Nom",
	ShortDescription: "Petite déscription",
	Description: "Déscription",
	Website: "Site Web",
	Editor: "Editeur",
	EditDescInEditor: "Editer une longue déscription",
	RichTextEditor: "Éditeur de texte enrichi",
	EditContentInEditor: "Edit content in editor",
	InvalidURL: "URL invalid",
	ImageRequired: "Images manquante",
	Translation: "Traduction",
	dataSaved: "Données enregistrer avec succée",
	dataDeleted: "Données supprimer avec succée",
	Cancel: "Annuler",
	Confirm: "confirmer",
	Search: "Recherche",
	TranslationKey: "Clé",
	SourceText: "text source",
	TargetText: "But du text",
	ProductOptions: "Options produit",
	ProductOptionsMembers: "Options produits membres",
	ProductOptionGroups: "Options produits groupes",
	AreYouSure: "Etes vous sur de continuer",
	Users: "utilisateurs",
	User: "utilisateur",
	IconSelector: "icon de séléction",
	MobileIcon: "icone mobile",
	Members: "membres",
	iconColor: "icon / couleur",
	color: "couleur",
	shortCode: "code miniature",
	Language: "Language",
	Info: "info",
	Security: "sécurité",
	PersonalInfo: "info personnel",
	Permissions: "Permissions",
	Permission: "Permission",
	LoginHistory: "historique de connexion",
	LoginAccount: "connexion au compte",
	Address1: "Address1",
	Address2: "Address2",
	CurrencyList: "liste devise",
	SelectPlace: "séléctionner place",
	Country: "pays",
	Countries: "pays",
	City: "wilayas",
	Area: "daîra",
	PassDontMatch: "mot de passe non compatible",
	ConfirmPassword: "confirmer mot de passe",
	InvalidPasswordFormat: "Le mot de passe doit contenir au moins une lettre majuscule, une lettre minuscule, un caractère spécial et un nombre",
	ETags: "eTags",
	ETag: "eTags",
	createNewetag: "créer un nouveau eTag",
	NS_NewOrder: "Nouvelle achat",
	NS_NewMessage: "nouveau message",
	NS_SecurityActions: "actions de sécurité",
	NS_Reviews: "Revues",
	NS_Questions: "Questions",
	NS_AskForPrice: "demander le prix",
	NS_AutoDiscount: "vente automatique",
	NS_StatisticsAlert: "alerte statistiques",
	Role: "Role",
	Warehouses: "Warehouses",
	AddUser: "Ajouter utilisateur",
	UserAlreadyExists: "utilisateur existant",
	Customers: "clients",
	NoneSelected: "Non séléctionné",
	Clear: "Vider",
	Type: "type",
	Status: "Status",
	Address: "Address",
	Store: "Store",
	Statistics: "statistique",
	VirtualMoney: "money virtuel",
	Spent: "dépensé",
	Gender: "Genre",
	Facebook: "Facebook",
	Twitter: "Twitter",
	Birthday: "Date de naissance",
	EnterConfirmCode: "Veuillez rentré la confirmation que vous venez de recevoire",
	IncorrectInput: "entrée incorecct",
	Roles: "Roles",
	MustHaveOneRole: "obligatoire d'avoir au moins un role",
	CanRead: "Lire",
	CanCreate: "crée",
	CanEdit: "Editer",
	CanDelete: "supprimer",
	Delete: "supprimer",
	CanExport: "exporter",
	Discounts: "ventes",
	Filters: "filtres",
	Active: "actif",
	Inactive: "inactif",
	Both: "tous",
	Customer: "clients",
	Courier: "courrier",
	Discount: "ventes",
	Select: "selectionner",
	ApplyFor: "appliquer pour",
	Restriction: "restriction",
	CouponCode: "code",
	RequiresCouponCode: "code demander",
	DiscountType: "type de vente",
	DiscountLimitation: "vente limiter",
	LimitationTimes: "temps limiter",
	DiscountPercentage: "pourcentage de vente",
	DiscountAmount: "montant de la remise",
	MaximumDiscountAmount: "montant maximum des remises",
	ShowInWebsite: "voir dans l'application",
	StartDate: "date de début",
	EndDate: "date de fin",
	IsCumulative: "accumulation",
	ApplyForChildCategory: "inclure les sous catégories",
	SpentAmountRestriction: "Montant dépensé",
	Shipping: "livraison",
	CouponCodeDuplicated: "code coupon dupliquer",
	Articles: "Articles",
	Article: "Article",
	ParentArticle: "article similaire",
	Icon: "Icon",
	Stories: "Stories",
	Story: "Story",
	Hours: "heures",
	Days: "jours",
	Weeks: "semaines",
	Length: "Longueur",
	Likes: "Likes",
	Views: "vues",
	TextColor: "couleur du text",
	BackgroundColor: "couleur de l'arriere plan",
	Summary: "sommaire",
	Items: "articles",
	Item: "article",
	TrackingHistory: "historique de suivi",
	Chat: "chat",
	SubTotal: "sous total",
	Tax: "TVA",
	Total: "Total",
	Details: "détails",
	CreatedDate: "date de création",
	DeliveredDate: "date de livraison",
	OrderCode: "code commande",
	Save: "enregistrer",
	Advance_Settings: "Paramétres avancée",
	Courier_Config: "courier de configuration",
	AdvanceSettings: "Paramétres avancée",
	Price: "Prix",
	RealPrice: "Prix réel",
	SalePrice: "prix de vente",
	SaleExpirationDate: "date d'expiration de la vente",
	MaxPurchaseCount: "Nombre d'achat maximum",
	Currency: "devise",
	priceSteps: "palier de prix",
	PricingHistory: "historique de prix",
	Pricing: "prix",
	Tags: "Tags",
	TypeNewTagHere: "tapper un nouveau tag ici",
	LowStep: "plus bas",
	HighStep: "plus haut",
	Add: "ajouter",
	UpdateCost: "Mettre à jour le coût",
	Where_Houses: "WareHouses",
	Shoping_Speed: "Shopping express",
	Quantity: "quantité",
	Change: "changer",
	FixedPrice: "fixer prix",
	KgPrice: "prix du KG",
	Key1: "clé 1",
	Key2: "clé 2",
	Key3: "clé 3 ",
	Key4: "clé 4 ",
	SecurityKey: "clé de sécurité",
	HavePutOneKey: "entrer au minimum une clé",
	PleaceSelectCites: "séléct wilaya",
	PleaceEnterKgPrice: "entrer prix du KG",
	ToCity: "a wilaya",
	ToArea: "a daîra",
	FromCity: "de wilaya",
	ToCountry: "a pays",
	FromCountry: "de pays",
	PleaceEnterFixedPrice: "entrer prix fixer",
	PleaceSelectWherehouse: "selectioner warehouse",
	PleaceSelectShoppingspeed: "selectioner achats rapid",
	ExtraDetails: "details supplementaire",
	DoneSuccessfully: "avec succée",
	Soon: "prochainement",
	SeeMore: "voir plus",
	SeeLess: "voir moins",
	CustomerType: "type de client",
	ResetPassword: "modifier mot de passe",
	SelectLanguage: "selectioner langue",
	overwrite: "Overwrite",
	Done: "fait",
	Images: "Images",
	isreplaceableimage: "image remplacable",
	AdminTranslation: "traduction de l'administrateur",
	AppTranslation: "traduction de l'application",
	SendAnswers: "envoyer",
	Answer: "ecrire reponse",
	AnswerSended: "votre reponse a était envoyer",
	Answers: "reponses",
	NoFilter: 'Pas de filtre',
	Approved: "Approuvé",
	NotApproved: 'Pas Approuvé',
	Replied: "Répondu",
	NotReplied: 'Pas Répondu',
	ReviewDate: 'Date De Révision',
	ApproveDate: 'Date d\'Approbation',
	OrderReview: "revue d'achat",
	OrderId: "revue ID",
	Reply: "repondre",
	ReplyText: "text de reponse",
	DiscountPercentageValue: "Le pourcentage de remise doit être inférieur ou égal à 100%",
	NegativeValidation: "vous ne pouver utuliser une valeur negative",
	DateValidation: "date d'expiration ne peut etre inferieur a la date de création",
	Location: "localisation",
	Rating: "noter",
	SKU: "SKU Is Required",
	ParentCategory: "catégorie similaire",
	selected: "selectioner",
	Physical: "physiquement",
	Settings: "parametres",
	Media: "média",
	Options: "Options",
	Numberofdownloadsperday: "nombre de téléchargement par jour",
	Numberofdaysdownloadavailable: "Nombre de jours de téléchargement disponibles",
	Purchasefile: "Fichier d'achat",
	Number: "Nombre",
	filetypenotsupported: "type de fichier non supporter",
	exceededfilesizelimit: "dépassé la limite de taille de fichier",
	nooptionsfound: "pas d'option trouver",
	Height: "taille",
	Weight: "poids",
	LocalLocation: "localisation local",
	ManufacturerPartNumber: "Référence fabricant",
	pleaseenteraprice: "veuilez entrer le prix",
	pleaseenterarealprice: "veuillez entrer le prix initial",
	Lowstepvaluecantbeempty: "valeur minimal ne peut etre vide",
	Highstepvaluecantbeempty: "la valeur maximal ne peut etre vide",
	Steppricevalue: "la valeur du prix ne peut etre vide",
	LowstepcantbelowerthanTwo: "valeur minimal ne peut etre inferieur a 2",
	Highstepmustbehigherthanlowstep: "valeur maximal dois etre superieur a la valeur minimal",
	Enablereviews: "activer les avis",
	Enablequestions: "activer les questions",
	Category: "Category",
	Etag: "Etag",
	PriceRange: "ranger de prix",
	RATINGRANAGE: "ranger d'avis",
	SelectProductType: "selectioner type de produits",
	SelectProductVisibility: "Sélectionnez la visibilité du produit",
	SelectCategory: "selectionnez la categorie",
	DataNotSaved: "ne pas enregistrer",
	Product: "produits",
	Howmany: "combien",
	in1usd: "en 1 USD",
	Text: "Text",
	Questions: "Questions",
	Reviews: "revues",
	QuestionText: "text question",
	Question: "Question",
	Demofile: "fichier démo",
	Visibility: "visibiliter",
	cantdownload: "ne peut etre télécharger",
	Width: "Width",
	StoreProfile: "Profile Magasin",
	StoreName: "Nom magasin",
	Profile: "Profile",
	Languages: "Languages",
	StoreListing: "liste des magasins",
	NOTIFICATIONS: "NOTIFICATIONS",
	label: "label",
	StoreList: "list magasin",
	NameOnStoreCantbeleththan3charchter: "nom du magasin ne peut etre inferieur a 3 lettres",
	LongDescriptionCantbeleththan3charchter: "la description ne peut etre inferieur a 30 characters",
	ShortDescriptionCantbeleththan3charchter: "la petite description ne peut dépasser 30 characters",
	LabelNameCantbeleththan3charchter: "nom de label ne peut avoir moins de 3 characters",
	LongDescription: "longue description",
	Theme: "theme",
	StoreStyle: "style du magasin",
	FontSizeValidation: "taille de police est comprise entre 10 et 30",
	MainColor: "Couleur principale",
	SecondColor: "couleur secondaire",
	ThirdColor: "troiziem couleur",
	Fonts: "polices",
	Color: "couleur",
	FontSize: "taille de police",
	FontType: "type de police",
	AuthThemeType: "auth type theme",
	StoreThemeType: "type théme magasin",
	UserThemeType: "type théme utilisateur",
	Sizes: "tailles",
	BorderRadius: "bordure reduites",
	Padding1: "Padding1",
	Padding2: "Padding2",
	Padding3: "Padding3",
	Margin1: "Margin1",
	Margin2: "Margin2",
	Margin3: "Margin3",
	Adress: "Address",
	Default: "Default",
	DefaultLanguage: "langue par defaut",
	SecondName: "nom secondaire",
	Email1: "Email1",
	Email2: "Email2",
	PostCode: "code postal",
	IsCompany: "companie",
	CompanyName: "nom de companie",
	SetDefault: "mettre par defaut",
	ShareAdress: "partager addrress",
	AddressHasBeenSet: "Address enregistrer",
	EnterCompanyName: "entrer nom de companie",
	Open: "ouvrire",
	Close: "fermer",
	WorkingHours: "heure de travaille",
	From: "de ",
	To: "a",
	IsOpen: "est ouvert",
	BasicInfo: "information basic",
	GpsCheckin: "GPS check",
	Warehouse: "Warehouse",
	ShippingTypes: "Type de livraison",
	AddWarehouse: "ajouter warehouse",
	Gps: "assurer vous d'avoir une connexion internet et que le GPS est activer",
	FullName: "nom complet",
	Pages: "Pages",
	MoreThanOne: "plus d'un",
	dataReset: "restaurer ",
	Defaultfont: "police par defaut",
	SubStore: "sous magasin",
	Payment: "Payment",
	Payment_Config: "Payment Config",
	FeesPercentage: "Pourcentage des frais",
	FeesFixed: "frais fix",
	ProviderKey1: "ProviderKey1",
	ProviderKey2: "ProviderKey2",
	ProviderKey3: "ProviderKey3",
	ProviderKey4: "ProviderKey4",
	GetPricing: "avoir le prix",
	NewOrder: "nouvel achat",
	Qty: "Quantité",
	AddProduct: "ajouter produits",
	Title: "titre",
	AddIcon: "ajouter icon",
	Driver: "Driver",
	IsRequired: "est requis",
	ProductOption: "option produits",
	Member: "membre",
	Group: "groupe",
	notselected: "non selectioner",
	Pricechange: "changer prix",
	AnswerNow: "reponse",
	Porvider: "fournisseur",
	Saving: "enregistrer",
	Comission: "Commission",
	IsDriver: "Is Driver",
	Intro: "Veuillez saisir certaines données nécessaires à la publication de votre application sur l'App Store",
	GoLive: "en direct",
	GoLiveTitle: "en direct",
	Info2: "Votre application sera disponible sur les App Stores après 2 semaines de saisie des données que nous vous avons demandées sur cette page",
	Sort: 'Arranger',
	SalesHigherFirst: 'Ventes (le plus élevée en premier)',
	SalesLowerFirst: 'Ventes (le plus bas en premier)',
	MostViews: 'Les plus vus',
	PriceHigherFirst: 'Prix (le plus élevé en premier)',
	PriceLowerFirst: 'Prix (le bas élevé en premier)',
	WhatsappAlert: 'S\'il vous plaît installer WhatsApp pour envoyer des messages directs Via WhatsApp',
	PhoneAlert: 'Le numéro de téléphone n\'est pas disponible',
	SetQty: 'Mettre la quantité',
	ShouldBeAPositiveNumber: ' Devrait être un nombre positif',
	OrdersStatuses: 'Status de l\'achat',
	OrdersStatus: 'Status des achats',
	OrderStatus: 'Status de l\'achat',
	ShownInCustomerList: 'Montré dans la liste des clients',
	StandardOrderCycle: 'Standard cycle de commande',
	CantBeDeleted: 'Ne peut pas être supprimé',
	ImageSizeError: 'La taille de l\'image doit être plus que ou égale à 700 * 700',
	ImageDimensionsError: 'La largeur de l\'image doit être égale à la hauteur de l\'image',
};
//!!!!!!!! KEY END !!!!!!!!

export const DEFAULT_LANGUAGE_ID = 2
export const DEFAULT_LANGUAGE_TRANSLATION = en
export const DEFAULT_LANGUAGE_CODE = 'en'