require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
install! 'cocoapods', :deterministic_uuids => false

target 'Admin' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
#    pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
    
    pod 'Firebase/Core', '~> 6.15.0'
    pod 'Firebase/Messaging', '~> 6.15.0'
    
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  target 'AdminTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Admin-tvOS' do
  # Pods for Admin-tvOS

  target 'Admin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
